### ISSUE TITLE
Requirements on RubyGems for Server not up-to-date

### ISSUE THREAD

**Issue by cubuzz** [kenichi/h2#6]
```C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- celluloid/current (LoadError)
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/h2-0.8.2/lib/h2/server.rb:1:in `<top (required)>'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
        from C:/Ruby24-x64/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from ./hook.rb:44:in `<main>'```

Can you make sure that requirements are updated?

**Comment by kenichi** [comment]
oh my - i completely missed this issue and haven't been working on this project in a while. my apologies! in this case, the server feature is optional, so the requirements are not baked into the gemspec, see https://github.com/kenichi/h2#server-usage.

my plan was to remove celluloid as a requirement completely, since it has been officially EOLed, but as you can see, the project has languished. another project i was looking at is https://github.com/socketry/falcon which i don't believe has any celluloid deps. sorry again for the late reply.
